name: worlad
description: An app that disaplays information about the world.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  path_provider: ^2.0.9
  fluttertoast: ^8.0.9
  logger: ^1.1.0
  sqflite: ^2.0.2+1
  intl: ^0.17.0
  animated_splash_screen: ^1.2.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_spinkit: ^5.1.0
  rflutter_alert: ^2.0.4
  gap: ^2.0.0
  device_preview: ^1.0.0
  analog_clock: ^0.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-UI-Regular.otf
        - asset: assets/fonts/Inter/Inter-UI-Bold.otf
      